"""Add users fk to project table

Revision ID: 1bd961c92b3a
Revises: 95a7e97103bf
Create Date: 2024-01-09 20:20:30.741716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd961c92b3a'
down_revision = '95a7e97103bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projects_users', 'users', ['users_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_users', type_='foreignkey')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###
