"""Update projects org table

Revision ID: 3c88eaea09f8
Revises: 9a1fa2fe510f
Create Date: 2024-01-09 16:18:46.936286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c88eaea09f8'
down_revision = '9a1fa2fe510f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_organisations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects', type_='foreignkey')
        batch_op.create_foreign_key('fk_projects', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_organisations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects', type_='foreignkey')
        batch_op.create_foreign_key('fk_projects', 'organisations', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
