"""users table

Revision ID: 6098f9e25c20
Revises: 
Create Date: 2024-01-09 10:45:26.217906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6098f9e25c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('cc_emails', sa.String(length=1000), nullable=True),
    sa.Column('failed_login_streak', sa.Integer(), server_default='0', nullable=True),
    sa.Column('mfa_secret', sa.String(length=100), nullable=True),
    sa.Column('mfa_secret_confirmed', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('pii_key_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_pii_key_id'), ['pii_key_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_pii_key_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
