"""Update projects table

Revision ID: 8904604d2ff3
Revises: 1bd961c92b3a
Create Date: 2024-01-09 20:22:40.463984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8904604d2ff3'
down_revision = '1bd961c92b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_projects_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_projects_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_projects_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_projects_users', 'users', ['users_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
