"""Add organisation_organisation

Revision ID: b210850997bc
Revises: 6eb156fc8b0e
Create Date: 2024-01-09 14:10:33.414621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b210850997bc'
down_revision = '6eb156fc8b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations_organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_organisation_id', sa.Integer(), nullable=False),
    sa.Column('child_organisation_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_organisation_id'], ['organisations.id'], name='fk_organisations_organisations_child_organisations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_organisation_id'], ['organisations.id'], name='fk_organisations_organisations_parent_organisations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_organisation_id', 'child_organisation_id', name='unique_parent_child_organisation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisations_organisations')
    # ### end Alembic commands ###
